# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd16e4222293cc38a085c586c8d1492be06df3239237d3a3de35c422fb52f74d89591c9071f0fee0d53547c05fe6f23283729c9dde927458b1d663df467a67a

test:
  secret_key_base: 820c6a22596bb6c288c7e6fe94549d6610b8b6d04e16fbe1e08ff3c51b9a005e88bf21b5cb94e212e3493e354ed928ee7f72df41c99edfc094d61a9cb732cad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
